name: fusewallet
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org. 
version: 2.0.2+13

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  web3dart: ^0.4.5
  barcode_scan: ^0.0.3
  shared_preferences: ^0.4.3
  qr_flutter:
    git:
      url: git://github.com/lukef/qr.flutter.git
  flutter_secure_storage: ^3.1.2
  intl: ^0.15.7
  absinthe_socket: ^0.0.2
  bip39: ^1.0.3
  bip32: ^1.0.5
  #flutter_nfc_reader:
  #  git:
  #    url: git://github.com/matteocrippa/flutter-nfc-reader.git
  #    ref: master
  country_code_picker: ^1.1.5
  firebase_auth: ^0.6.2+1
#  local_auth: ^0.4.0+1
  
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:

  assets:
    - images/
    - data/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:

  fonts:
    - family: Gotham
      fonts:
        - asset: fonts/GothamBook.ttf
        - asset: fonts/GothamLight.ttf
          weight: 300
        - asset: fonts/GothamLight.ttf
          weight: 400
        - asset: fonts/GothamBook.ttf
          weight: 600
        - asset: fonts/GothamMedium_0.ttf
          weight: 700
        - asset: fonts/GothamBold.ttf
          weight: 800
        - asset: fonts/GothamBold.ttf
          weight: 900

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
